const { chromium } = require('playwright-core');
const { STUB_URL, EXE, SRC: PLUGIN_PATH } = require('../util');
const PLUGIN = require('fs').readFileSync(PLUGIN_PATH, 'utf8');
const errors = [];
(async () => {
  const browser = await chromium.launch({ executablePath: EXE });
  const p = await browser.newPage({ viewport: { width: 430, height: 900 } });
  p.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
  await p.goto(STUB_URL);
  await p.evaluate(() => { localStorage.setItem('hs_run','1'); localStorage.removeItem('hs_ov'); });
  await p.reload();
  await p.addScriptTag({ content: PLUGIN });
  await p.waitForTimeout(3000);
  const shot = async n => await p.screenshot({ path: '/tmp/protoshots/r-' + n + '.png' });
  const t = (name, ok) => console.log((ok ? '✅' : '❌') + ' ' + name) || (!ok && errors.push('FAIL: ' + name));
  const btns = await p.evaluate(() => [...document.querySelectorAll('#hs_actions .btn')].map(b => b.textContent));
  t('卡片按钮=停止,分流,节点', JSON.stringify(btns) === JSON.stringify(['停止','分流','节点']));
  await shot('01-card');
  await p.click('#hs_status');
  await p.waitForTimeout(800);
  t('状态行点击开面板', await p.evaluate(() => document.querySelector('#hs_modal_mgr').style.display !== 'none'));
  const tabs = await p.evaluate(() => [...document.querySelectorAll('#hs_mgr_tabs button[data-t]')].map(b => b.textContent));
  t('页签=状态/分流/节点/订阅/设置/日志(平铺直达)', JSON.stringify(tabs) === JSON.stringify(['状态','分流','节点','订阅','设置','日志']));
  t('状态页显示操作栏', await p.evaluate(() => document.querySelector('#hs_mgr_foot').style.display !== 'none'));
  /* 操作栏 flex 布局(v1.8.3 修复回归) */
  const foot = await p.evaluate(() => { const f = document.querySelector('#hs_mgr_foot'); return getComputedStyle(f).display + '/' + getComputedStyle(f).justifyContent; });
  t('操作栏 flex 布局(靠右)', foot === 'flex/flex-end');
  await shot('02-tab-stat');
  await p.click('#hs_mgr_tabs button[data-t="split"]');
  await p.waitForTimeout(1500);
  t('分流页含设备区(2台)', await p.evaluate(() => document.querySelectorAll('#hs_dev_pane .hs-devrow').length) === 2);
  t('分流页隐藏操作栏', await p.evaluate(() => document.querySelector('#hs_mgr_foot').style.display === 'none'));
  await shot('03-tab-split-dev');
  await p.click('#hs_mgr_tabs button[data-t="node"]');
  await p.waitForTimeout(1200);
  t('节点页有管理订阅按钮', await p.evaluate(() => !!document.querySelector('#hs_node_submgr')));
  await shot('04-tab-node');
  await p.click('#hs_node_submgr');
  await p.waitForTimeout(600);
  t('管理订阅→订阅页签直达', await p.evaluate(() => !!document.querySelector('#hs_sub_name')) && await p.evaluate(() => document.querySelector('#hs_mgr_tabs button[data-t="sub"]').classList.contains('on')));
  await shot('05-tab-sub');
  await p.click('#hs_mgr_tabs button[data-t="set"]');
  await p.waitForTimeout(800);
  t('设置页直达且含卸载入口(危险区)', await p.evaluate(() => !!document.querySelector('#hs_set_un')));
  /* 策略来源三段 UI */
  t('策略来源三段(自建/合并/直通)', await p.evaluate(() => { const seg = document.querySelector('#hs_seg_policy'); return seg && seg.querySelectorAll('button').length === 3; }));
  await shot('06-tab-set');
  await p.click('#hs_mgr_tabs button[data-t="log"]');
  await p.waitForTimeout(600);
  /* v2.0.3: 关闭态默认落操作日志页签(运行日志引导横幅) */
  t('日志页关闭态=操作日志页签(运行日志引导)', await p.evaluate(() => document.body.textContent.includes('操作日志')));
  await p.evaluate(() => { hsLogTab = 'run'; });
  await p.evaluate(() => window.renderPane ? renderPane() : 0);
  await p.waitForTimeout(400);
  t('运行日志 tab 关闭态引导', await p.evaluate(() => document.body.textContent.includes('运行日志已关闭') || document.body.textContent.includes('日志记录已关闭')));
  await p.evaluate(() => { const en = document.querySelector('#hs_log_enable'); if (en) en.click(); else { hsLogTab = 'op'; } });
  await p.waitForTimeout(600);
  await p.evaluate(() => { const no = document.querySelector('#hs_cf_no'); if (no) no.click(); });
  await p.waitForTimeout(1500);
  await p.evaluate(() => { const m = document.querySelector('#hs_modal_mgr'); if (m) m.style.display = 'none'; });
  await p.waitForTimeout(300);
  t('开日志后卡片出现日志按钮', await p.evaluate(() => [...document.querySelectorAll('#hs_actions .btn')].some(b => b.textContent === '日志')));
  await shot('08-card-logbtn');
  console.log('----');
  console.log(errors.length ? errors.join('\n') : 'ALL CLEAN');
  await browser.close();
  process.exit(errors.length ? 1 : 0);
})().catch(e => { console.error('FATAL:', e.message); process.exit(1); });
